// <auto-generated />
using Basic_Battle_RESTful_Service.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Basic_Battle_RESTful_Service.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Basic_Battle_RESTful_Service.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BlueID");

                    b.Property<int>("RedID");

                    b.Property<int>("WhichPlayer");

                    b.Property<int>("WinnerID");

                    b.HasKey("Id");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("Basic_Battle_RESTful_Service.Models.GamePlayerInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Armour");

                    b.Property<int>("GameID");

                    b.Property<int>("Health");

                    b.Property<int>("PlayerID");

                    b.HasKey("ID");

                    b.ToTable("GamePlayerInfo");
                });

            modelBuilder.Entity("Basic_Battle_RESTful_Service.Models.MatchLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Description");

                    b.Property<int>("GameID");

                    b.HasKey("Id");

                    b.ToTable("MatchLog");
                });

            modelBuilder.Entity("Basic_Battle_RESTful_Service.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArmorRate");

                    b.Property<int>("Damage");

                    b.Property<int>("HealthRate");

                    b.Property<string>("Name");

                    b.Property<bool>("SelectedCharacter");

                    b.Property<int>("SpecialAttackDamage");

                    b.Property<int>("SpecialAttackDamage1");

                    b.Property<string>("SpecialAttackName");

                    b.Property<string>("SpecialAttackName1");

                    b.HasKey("Id");

                    b.ToTable("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
